services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - internal
    restart: always

  app:
    build:
      context: .
    container_name: finance-wallet-api
    networks:
      - internal
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    restart: always

networks:
  internal:
    driver: bridge
